import fs from "fs/promises";
import path from "path";

export const generateProject = async (
  projectType,
  projectSubType,
  projectName,
) => {
  const targetDir = path.join(process.cwd(), "projects", projectName);

  // Make directory
  await fs.mkdir(targetDir, { recursive: true });

  if (projectType === "React") {
    if (projectSubType === "TypeScript") {
      await generateReactTS(targetDir, projectName);
    } else {
      await generateReactJS(targetDir, projectName);
    }
  } else if (projectType === "Express API") {
    await generateExpressAPI(targetDir, projectName);
  } else if (projectType === "Node CLI") {
    await generateNodeCLI(targetDir, projectName);
  }
};

const generateReactTS = async (dir, name) => {
  const packageJson = {
    name,
    version: "1.0.0",
    type: "module",
    scripts: {
      dev: "vite",
      build: "tsc && vite build",
      preview: "vite preview",
    },
    dependencies: {
      react: "^18.2.0",
      "react-dom": "^18.2.0",
    },
    devDependencies: {
      "@types/react": "^18.2.66",
      "@types/react-dom": "^18.2.22",
      "@vitejs/plugin-react": "^4.2.1",
      typescript: "^5.2.2",
      vite: "^5.2.0",
    },
  };

  await fs.writeFile(
    path.join(dir, "package.json"),
    JSON.stringify(packageJson, null, 2),
  );
  await fs.writeFile(
    path.join(dir, "index.html"),
    `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite + React + TS</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`,
  );

  const srcDir = path.join(dir, "src");
  await fs.mkdir(srcDir, { recursive: true });

  await fs.writeFile(
    path.join(srcDir, "main.tsx"),
    `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)`,
  );

  await fs.writeFile(
    path.join(srcDir, "App.tsx"),
    `function App() {
  return (
    <div>
      <h1>${name} (React TS)</h1>
      <p>Project skeleton generated by Dev-CLI.</p>
    </div>
  )
}
export default App`,
  );

  await fs.writeFile(
    path.join(dir, "vite.config.ts"),
    `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})`,
  );

  await fs.writeFile(
    path.join(dir, ".gitignore"),
    `node_modules
dist
.env
`,
  );

  await fs.writeFile(
    path.join(dir, "tsconfig.json"),
    `{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"]
}`,
  );
};

const generateReactJS = async (dir, name) => {
  const packageJson = {
    name,
    version: "1.0.0",
    type: "module",
    scripts: {
      dev: "vite",
      build: "vite build",
      preview: "vite preview",
    },
    dependencies: {
      react: "^18.2.0",
      "react-dom": "^18.2.0",
    },
    devDependencies: {
      "@vitejs/plugin-react": "^4.2.1",
      vite: "^5.2.0",
    },
  };

  await fs.writeFile(
    path.join(dir, "package.json"),
    JSON.stringify(packageJson, null, 2),
  );
  await fs.writeFile(
    path.join(dir, "index.html"),
    `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite + React</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>`,
  );

  const srcDir = path.join(dir, "src");
  await fs.mkdir(srcDir, { recursive: true });

  await fs.writeFile(
    path.join(srcDir, "main.jsx"),
    `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)`,
  );

  await fs.writeFile(
    path.join(srcDir, "App.jsx"),
    `function App() {
  return (
    <div>
      <h1>${name} (React JS)</h1>
      <p>Project skeleton generated by Dev-CLI.</p>
    </div>
  )
}
export default App`,
  );

  await fs.writeFile(
    path.join(dir, "vite.config.js"),
    `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})`,
  );

  await fs.writeFile(
    path.join(dir, ".gitignore"),
    `node_modules
dist
.env
`,
  );
};

const generateExpressAPI = async (dir, name) => {
  const packageJson = {
    name,
    version: "1.0.0",
    type: "module",
    scripts: {
      start: "node src/index.js",
      dev: "node --watch src/index.js",
    },
    dependencies: {
      express: "^4.19.2",
      cors: "^2.8.5",
      dotenv: "^16.4.5",
    },
  };

  await fs.writeFile(
    path.join(dir, "package.json"),
    JSON.stringify(packageJson, null, 2),
  );

  const srcDir = path.join(dir, "src");
  await fs.mkdir(srcDir, { recursive: true });

  await fs.writeFile(
    path.join(srcDir, "index.js"),
    `import express from "express";
import cors from "cors";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

app.get("/", (req, res) => {
  res.json({ message: "Welcome to ${name} API!" });
});

app.listen(PORT, () => {
  console.log(\`Server is running on http://localhost:\${PORT}\`);
});
`,
  );

  await fs.writeFile(path.join(dir, ".env"), `PORT=3000\n`);
};

const generateNodeCLI = async (dir, name) => {
  const packageJson = {
    name,
    version: "1.0.0",
    type: "module",
    bin: {
      [name]: "./bin/index.js",
    },
    scripts: {
      start: "node bin/index.js",
    },
    dependencies: {
      commander: "^12.0.0",
      chalk: "^5.3.0",
      inquirer: "^9.2.15",
    },
  };

  await fs.writeFile(
    path.join(dir, "package.json"),
    JSON.stringify(packageJson, null, 2),
  );

  const binDir = path.join(dir, "bin");
  await fs.mkdir(binDir, { recursive: true });

  const assetsDir = path.join(dir, "assets");
  await fs.mkdir(assetsDir, { recursive: true });

  // Crear la base de src y sus subdirectorios
  const srcDir = path.join(dir, "src");
  await fs.mkdir(path.join(srcDir, "commands"), { recursive: true });
  await fs.mkdir(path.join(srcDir, "ui"), { recursive: true });
  await fs.mkdir(path.join(srcDir, "data"), { recursive: true });
  await fs.mkdir(path.join(srcDir, "utils"), { recursive: true });

  await fs.writeFile(
    path.join(binDir, "index.js"),
    `#!/usr/bin/env node

import { program } from "commander";
import chalk from "chalk";

program
  .name("${name}")
  .description("CLI generated by Dev-CLI")
  .version("1.0.0");

program
  .command("hello")
  .description("Say hello")
  .action(() => {
    console.log(chalk.green("Hello from ${name} CLI!"));
  });

program.parse(process.argv);
`,
  );
};
